#!/usr/bin/env python3
"""Species photos for the full view (owner, 2026-09-29).

Reads pipeline/species_images.json (the owner's picks, CC0 or CC BY 4.0, with
their attribution), downloads each image, crops it square, converts it to
greyscale with a 1 % contrast stretch and writes:

- worker/photos/<taxon>.jpg, 480 x 480 (the half views show it at up to about 500 px on the X, owner 2026-09-30), the files served at /photo/<taxon>.jpg
- worker/src/photos.js, the same bytes as base64, so the Worker needs no
  asset binding and the tests can load it as a plain module.

Cropping and greyscale are modifications: the credits say so (CC BY 4.0,
section 3(a)(1)(B)). Needs Pillow and network access.
"""
import base64, io, json, os, urllib.request
from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIZE = 480
# Off-centre crops, where the centre square cut the animal (checked by eye 2026-09-29).
CENTER = {"Caretta caretta": (0.68, 0.5), "Pandion haliaetus": (0.2, 0.5)}


def slug(taxon):
    return taxon.lower().replace(" ", "_")


def main():
    picks = json.load(open(os.path.join(ROOT, "pipeline", "species_images.json"), encoding="utf-8"))["species"]
    os.makedirs(os.path.join(ROOT, "worker", "photos"), exist_ok=True)
    out = {}
    for taxon, v in picks.items():
        req = urllib.request.Request(v["image"], headers={"User-Agent": "OnTheMoveTRMNL/0.1 (https://github.com/nikokoren/on_the_move)"})
        im = Image.open(io.BytesIO(urllib.request.urlopen(req, timeout=60).read())).convert("RGB")
        sq = ImageOps.fit(im, (SIZE, SIZE), method=Image.LANCZOS, centering=CENTER.get(taxon, (0.5, 0.5)))
        g = ImageOps.autocontrast(ImageOps.grayscale(sq), cutoff=1)
        buf = io.BytesIO()
        g.save(buf, "JPEG", quality=82, optimize=True)
        open(os.path.join(ROOT, "worker", "photos", slug(taxon) + ".jpg"), "wb").write(buf.getvalue())
        out[slug(taxon)] = base64.b64encode(buf.getvalue()).decode()
    with open(os.path.join(ROOT, "worker", "src", "photos.js"), "w") as f:
        f.write("// Generated by pipeline/build_photos.py from pipeline/species_images.json. Do not edit.\n")
        f.write("// Greyscale " + str(SIZE) + " x " + str(SIZE) + " JPEGs, base64; credits in template/settings.yml and README.md.\n")
        f.write("export const PHOTOS = " + json.dumps(out, indent=1) + ";\n")
    print(len(out), "photos,", sum(len(b) for b in out.values()) // 1024, "KB base64")


if __name__ == "__main__":
    main()
