// Place names as the recipe writes them (owner, 2026-09-30), keyed by the
// source's English name (Natural Earth, via pipeline/build_featured.py).
//   de, en: a common short form where the source's name is long ("USA",
//           "Pazifik"); absent means the source's name stands.
//   inDe, inEn: "in" with the place, with its article or preposition ("im
//           Sudan", "in den USA", "auf Kuba", "in the Pacific"), for the list's
//           sentences ("Im Winterquartier in Spanien", "Wintering in Spain").
// Hand-written; worker/check.mjs fails if a place in the data has no entry.
export const PLACES = {
  "Spain": { inDe: "in Spanien", inEn: "in Spain" },
  "France": { inDe: "in Frankreich", inEn: "in France" },
  "Switzerland": { inDe: "in der Schweiz", inEn: "in Switzerland" },
  "Germany": { inDe: "in Deutschland", inEn: "in Germany" },
  "Morocco": { inDe: "in Marokko", inEn: "in Morocco" },
  "Poland": { inDe: "in Polen", inEn: "in Poland" },
  "Lithuania": { inDe: "in Litauen", inEn: "in Lithuania" },
  "Israel": { inDe: "in Israel", inEn: "in Israel" },
  "Lebanon": { inDe: "im Libanon", inEn: "in Lebanon" },
  "Syria": { inDe: "in Syrien", inEn: "in Syria" },
  "Turkey": { inDe: "in der Türkei", inEn: "in Turkey" },
  "Russia": { inDe: "in Russland", inEn: "in Russia" },
  "Georgia": { inDe: "in Georgien", inEn: "in Georgia" },
  "Liberia": { inDe: "in Liberia", inEn: "in Liberia" },
  "Guinea": { inDe: "in Guinea", inEn: "in Guinea" },
  "Mali": { inDe: "in Mali", inEn: "in Mali" },
  "Sahara": { inDe: "in der Sahara", inEn: "in the Sahara" },
  "Ivory Coast": { inDe: "in der Elfenbeinküste", inEn: "in Ivory Coast" },
  "Cameroon": { inDe: "in Kamerun", inEn: "in Cameroon" },
  "Nigeria": { inDe: "in Nigeria", inEn: "in Nigeria" },
  "Benin": { inDe: "in Benin", inEn: "in Benin" },
  "Ténéré": { inDe: "in der Ténéré", inEn: "in the Ténéré" },
  "Tunisia": { inDe: "in Tunesien", inEn: "in Tunisia" },
  "Italy": { inDe: "in Italien", inEn: "in Italy" },
  "Croatia": { inDe: "in Kroatien", inEn: "in Croatia" },
  "Bosnia and Herzegovina": { inDe: "in Bosnien und Herzegowina", inEn: "in Bosnia and Herzegovina" },
  "Hungary": { inDe: "in Ungarn", inEn: "in Hungary" },
  "Belarus": { inDe: "in Belarus", inEn: "in Belarus" },
  "Latvia": { inDe: "in Lettland", inEn: "in Latvia" },
  "Ukraine": { inDe: "in der Ukraine", inEn: "in Ukraine" },
  "Moldova": { de: "Moldau", inDe: "in Moldau", inEn: "in Moldova" },
  "Romania": { inDe: "in Rumänien", inEn: "in Romania" },
  "Bulgaria": { inDe: "in Bulgarien", inEn: "in Bulgaria" },
  "Palestine": { inDe: "in Palästina", inEn: "in Palestine" },
  "Egypt": { inDe: "in Ägypten", inEn: "in Egypt" },
  "Libyan Desert": { inDe: "in der Libyschen Wüste", inEn: "in the Libyan Desert" },
  "Sudan": { inDe: "im Sudan", inEn: "in Sudan" },
  "Central African Republic": { inDe: "in der Zentralafrikanischen Republik", inEn: "in the Central African Republic" },
  "Democratic Republic of the Congo": { de: "DR Kongo", en: "DR Congo", inDe: "in der DR Kongo", inEn: "in DR Congo" },
  "Republic of the Congo": { en: "Congo", inDe: "in der Republik Kongo", inEn: "in Congo" },
  "Sweden": { inDe: "in Schweden", inEn: "in Sweden" },
  "Denmark": { inDe: "in Dänemark", inEn: "in Denmark" },
  "Libya": { inDe: "in Libyen", inEn: "in Libya" },
  "Greece": { inDe: "in Griechenland", inEn: "in Greece" },
  "Serbia": { inDe: "in Serbien", inEn: "in Serbia" },
  "Austria": { inDe: "in Österreich", inEn: "in Austria" },
  "Czech Republic": { en: "Czechia", inDe: "in Tschechien", inEn: "in Czechia" },
  "North Macedonia": { inDe: "in Nordmazedonien", inEn: "in North Macedonia" },
  "Chad": { inDe: "im Tschad", inEn: "in Chad" },
  "Tassili oua-n-Ahaggar": { inDe: "im Tassili oua-n-Ahaggar", inEn: "in the Tassili oua-n-Ahaggar" },
  "Malta": { inDe: "auf Malta", inEn: "in Malta" },
  "Slovakia": { inDe: "in der Slowakei", inEn: "in Slovakia" },
  "Algeria": { inDe: "in Algerien", inEn: "in Algeria" },
  "Burkina Faso": { inDe: "in Burkina Faso", inEn: "in Burkina Faso" },
  "Atlantic Ocean": { de: "Atlantik", en: "Atlantic", inDe: "im Atlantik", inEn: "in the Atlantic" },
  "Bay of Biscay": { inDe: "in der Biskaya", inEn: "in the Bay of Biscay" },
  "Netherlands": { inDe: "in den Niederlanden", inEn: "in the Netherlands" },
  "Belgium": { inDe: "in Belgien", inEn: "in Belgium" },
  "Portugal": { inDe: "in Portugal", inEn: "in Portugal" },
  "South Africa": { inDe: "in Südafrika", inEn: "in South Africa" },
  "Ethiopia": { inDe: "in Äthiopien", inEn: "in Ethiopia" },
  "Somalia": { inDe: "in Somalia", inEn: "in Somalia" },
  "Somaliland": { inDe: "in Somaliland", inEn: "in Somaliland" },
  "Yemen": { inDe: "im Jemen", inEn: "in Yemen" },
  "Syrian Desert": { inDe: "in der Syrischen Wüste", inEn: "in the Syrian Desert" },
  "Iraq": { inDe: "im Irak", inEn: "in Iraq" },
  "Turkish Republic of Northern Cyprus": { de: "Nordzypern", en: "Northern Cyprus", inDe: "in Nordzypern", inEn: "in Northern Cyprus" },
  "Angola": { inDe: "in Angola", inEn: "in Angola" },
  "Namibia": { inDe: "in Namibia", inEn: "in Namibia" },
  "Kalahari Desert": { en: "Kalahari", inDe: "in der Kalahari", inEn: "in the Kalahari" },
  "Botswana": { inDe: "in Botswana", inEn: "in Botswana" },
  "Mozambique": { inDe: "in Mosambik", inEn: "in Mozambique" },
  "Mozambique Channel": { inDe: "in der Straße von Mosambik", inEn: "in the Mozambique Channel" },
  "Comoros": { inDe: "auf den Komoren", inEn: "in the Comoros" },
  "Indian Ocean": { inDe: "im Indischen Ozean", inEn: "in the Indian Ocean" },
  "Saudi Arabia": { inDe: "in Saudi-Arabien", inEn: "in Saudi Arabia" },
  "Jordan": { inDe: "in Jordanien", inEn: "in Jordan" },
  "Cyprus": { de: "Zypern", inDe: "auf Zypern", inEn: "in Cyprus" },
  "Mediterranean Sea": { en: "Mediterranean", inDe: "im Mittelmeer", inEn: "in the Mediterranean" },
  "South Sudan": { inDe: "im Südsudan", inEn: "in South Sudan" },
  "Black Sea": { inDe: "im Schwarzen Meer", inEn: "in the Black Sea" },
  "Baltic Sea": { inDe: "in der Ostsee", inEn: "in the Baltic Sea" },
  "Tanzania": { inDe: "in Tansania", inEn: "in Tanzania" },
  "Zambia": { inDe: "in Sambia", inEn: "in Zambia" },
  "Zimbabwe": { inDe: "in Simbabwe", inEn: "in Zimbabwe" },
  "Tyrrhenian Sea": { inDe: "im Tyrrhenischen Meer", inEn: "in the Tyrrhenian Sea" },
  "Niger": { inDe: "im Niger", inEn: "in Niger" },
  "Australia": { inDe: "in Australien", inEn: "in Australia" },
  "Timor Sea": { inDe: "in der Timorsee", inEn: "in the Timor Sea" },
  "Indonesia": { inDe: "in Indonesien", inEn: "in Indonesia" },
  "Banda Sea": { inDe: "in der Bandasee", inEn: "in the Banda Sea" },
  "Pacific Ocean": { de: "Pazifik", en: "Pacific", inDe: "im Pazifik", inEn: "in the Pacific" },
  "Philippine Sea": { inDe: "in der Philippinensee", inEn: "in the Philippine Sea" },
  "People's Republic of China": { de: "China", en: "China", inDe: "in China", inEn: "in China" },
  "North Korea": { inDe: "in Nordkorea", inEn: "in North Korea" },
  "Sea of Okhotsk": { inDe: "im Ochotskischen Meer", inEn: "in the Sea of Okhotsk" },
  "South Korea": { inDe: "in Südkorea", inEn: "in South Korea" },
  "Celebes Sea": { inDe: "in der Celebessee", inEn: "in the Celebes Sea" },
  "Philippines": { inDe: "auf den Philippinen", inEn: "in the Philippines" },
  "Yellow Sea": { inDe: "im Gelben Meer", inEn: "in the Yellow Sea" },
  "Japan": { inDe: "in Japan", inEn: "in Japan" },
  "East China Sea": { inDe: "im Ostchinesischen Meer", inEn: "in the East China Sea" },
  "Guatemala": { inDe: "in Guatemala", inEn: "in Guatemala" },
  "Mexico": { inDe: "in Mexiko", inEn: "in Mexico" },
  "United States of America": { de: "USA", en: "USA", inDe: "in den USA", inEn: "in the USA" },
  "Canada": { inDe: "in Kanada", inEn: "in Canada" },
  "Brazil": { inDe: "in Brasilien", inEn: "in Brazil" },
  "Bolivia": { inDe: "in Bolivien", inEn: "in Bolivia" },
  "Peru": { inDe: "in Peru", inEn: "in Peru" },
  "Colombia": { inDe: "in Kolumbien", inEn: "in Colombia" },
  "Panama": { inDe: "in Panama", inEn: "in Panama" },
  "Costa Rica": { inDe: "in Costa Rica", inEn: "in Costa Rica" },
  "Nicaragua": { inDe: "in Nicaragua", inEn: "in Nicaragua" },
  "El Salvador": { inDe: "in El Salvador", inEn: "in El Salvador" },
  "Honduras": { inDe: "in Honduras", inEn: "in Honduras" },
  "Sonoran Desert": { inDe: "in der Sonora-Wüste", inEn: "in the Sonoran Desert" },
  "Chihuahuan Desert": { inDe: "in der Chihuahua-Wüste", inEn: "in the Chihuahuan Desert" },
  "Gulf of Mexico": { inDe: "im Golf von Mexiko", inEn: "in the Gulf of Mexico" },
  "Cuba": { inDe: "auf Kuba", inEn: "in Cuba" },
  "Caribbean Sea": { de: "Karibik", en: "Caribbean", inDe: "in der Karibik", inEn: "in the Caribbean" },
  "Venezuela": { inDe: "in Venezuela", inEn: "in Venezuela" },
  "Jamaica": { inDe: "auf Jamaika", inEn: "in Jamaica" },
  "Haiti": { inDe: "in Haiti", inEn: "in Haiti" },
  "Dominican Republic": { inDe: "in der Dominikanischen Republik", inEn: "in the Dominican Republic" },
  "Hudson Strait": { inDe: "in der Hudsonstraße", inEn: "in the Hudson Strait" },
  "Florida Strait": { inDe: "in der Floridastraße", inEn: "in the Florida Strait" },
  "Hudson Bay": { inDe: "in der Hudson Bay", inEn: "in Hudson Bay" },
  "Sargasso Sea": { inDe: "in der Sargassosee", inEn: "in the Sargasso Sea" },
  "The Bahamas": { en: "Bahamas", inDe: "auf den Bahamas", inEn: "in the Bahamas" },
  "Aruba": { inDe: "auf Aruba", inEn: "in Aruba" },
  "Curaçao": { inDe: "auf Curaçao", inEn: "in Curaçao" },
  "Turks and Caicos Islands": { inDe: "auf den Turks- und Caicosinseln", inEn: "in the Turks and Caicos Islands" },
  "Gulf of California": { inDe: "im Golf von Kalifornien", inEn: "in the Gulf of California" },
  "Sea of Japan": { inDe: "im Japanischen Meer", inEn: "in the Sea of Japan" },
  "Seto Inland Sea": { inDe: "in der Seto-Inlandsee", inEn: "in the Seto Inland Sea" },
  "Korea Strait": { inDe: "in der Koreastraße", inEn: "in the Korea Strait" },
  "Davis Strait": { inDe: "in der Davisstraße", inEn: "in the Davis Strait" },
  "Greenland": { inDe: "auf Grönland", inEn: "in Greenland" },
  "Labrador Sea": { inDe: "in der Labradorsee", inEn: "in the Labrador Sea" },
  "Belize": { inDe: "in Belize", inEn: "in Belize" },
  "Bay of Campeche": { de: "Golf von Campeche", inDe: "im Golf von Campeche", inEn: "in the Bay of Campeche" },
  "Baffin Bay": { inDe: "in der Baffin Bay", inEn: "in Baffin Bay" }
};
